In [2]:
import numpy as np
import pprint

The transformation becomes from (w,b) - (x,1)

In [18]:
bias = 0.5
inputs = np.array([ 0.5, -0.5 ])
weights = np.array([ 2, -1 ])
target = 0

wt = np.append(weights, bias)
wt2 = wt+2
print(wt)
print(wt2)
ie = np.append(inputs, 1)

[ 2.  -1.   0.5]
[ 4.   1.   2.5]


In [19]:
result = wt.transpose() - ie
result2 = wt2.transpose() - ie

In [20]:
print('transformation step 1\n - {}'.format(result))

transformation step 1
 - [ 1.5 -0.5 -0.5]


In [21]:
result2

array([ 3.5,  1.5,  1.5])